version: '3.8'

services:

  product-service-05:
    build: ./product_service
    container_name: product-service-05
    ports:
      - "8005:8000"

  order-service-05:
    build: ./order_service
    container_name: order-service-05
    ports:
      - "9005:8000"
    depends_on:
      - product-service-05