name: Automated API Tests

on: [push]

jobs:

  test-microservices:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Start Docker Compose
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 15

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run collection.json